In [1]:
!pip install pdfplumber pytesseract pdf2image
!apt-get install tesseract-ocr

Collecting pdfplumber
  Downloading pdfplumber-0.11.8-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 1.5 MB/s eta 0:00:00
Collecting pytesseract
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Collecting pdf2image
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Collecting pdfminer.six==20251107 (from pdfplumber)
  Downloading pdfminer_six-20251107-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-5.2.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.8/67.8 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251107->pdfplumber) (3.4.4)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251107->pdfplumber) (43.0.3)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from pytesseract) (25.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (2.23)
Downloading pdfplumber-0.11.8-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 2.3 MB/s eta 0:00:00
Downloading pdfminer_six-20251107-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 43.9 MB/s eta 0:00:00
Downloading pytesseract-0.3.13-py3-none-any.whl (14 kB)
Downloading pdf2image-1.17.0-py3-none-any.whl (11 kB)
Downloading pypdfium2-5.2.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 46.6 MB/s eta 0:00:00
Installing collected packages: pytesseract, pypdfium2, pdf2image, pdfminer.six, pdfplumber
Successfully installed pdf2image-1.17.0 pdfminer.six-20251107 pdfplumber-0.11.8 pypdfium2-5.2.0 pytesseract-0.3.13
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

In [2]:
from google.colab import files
uploaded = files.upload()

Saving CBC-lab-example report.pdf to CBC-lab-example report.pdf
Saving complete blood count report.pdf to complete blood count report.pdf
Saving Full body Report.pdf to Full body Report.pdf

In [3]:
import os
os.listdir()

['.config',
 'Full body Report.pdf',
 'complete blood count report.pdf',
 'CBC-lab-example report.pdf',
 'sample_data']

In [4]:
!apt-get install -y poppler-utils

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  poppler-utils
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 186 kB of archives.
After this operation, 697 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 poppler-utils amd64 22.02.0-2ubuntu0.12 [186 kB]
Fetched 186 kB in 1s (161 kB/s)
Selecting previously unselected package poppler-utils.
(Reading database ... 117528 files and directories currently installed.)
Preparing to unpack .../poppler-utils_22.02.0-2ubuntu0.12_amd64.deb ...
Unpacking poppler-utils (22.02.0-2ubuntu0.12) ...
Setting up poppler-utils (22.02.0-2ubuntu0.12) ...
Processing triggers for man-db (2.10.2-1) ...

In [5]:
!pip install pdfplumber pandas

Requirement already satisfied: pdfplumber in /usr/local/lib/python3.12/dist-packages (0.11.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: pdfminer.six==20251107 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (20251107)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Requirement already satisfied: pypdfium2>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (5.2.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251107->pdfplumber) (3.4.4)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251107->pdfplumber) (43.0.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (2.23)

In [6]:
import pdfplumber

pdf_path = "CBC-lab-example report.pdf"

cbc_text = ""

with pdfplumber.open(pdf_path) as pdf:
    for page in pdf.pages:
        txt = page.extract_text()
        cbc_text += txt + "\n"

print(cbc_text)

WARNING:pdfminer.pdfinterp:Cannot set gray stroke color because /'P29' is an invalid float value
WARNING:pdfminer.pdfinterp:Cannot set gray non-stroke color because /'P29' is an invalid float value

DRLOGY PATHOLOGY LAB
0123456789 | 0912345678
drlogypathlab@drlogy.com
Accurate | Caring | Instant
105 -108, SMART VISION COMPLEX, HEALTHCARE ROAD, OPPOSITE HEALTHCARE COMPLEX. MUMBAI - 689578
www.drlogy.com
Yash M. Patel Sample Collected At:
Age : 21 Years 125, Shivam Bungalow, S G Road,
Registered on: 02:31 PM 02 Dec, 2X
Mumbai
Sex : Male
Collected on: 03:11 PM 02 Dec, 2X
PID : 555 Ref. By: Dr. Hiren Shah Reported on: 04:35 PM 02 Dec, 2X
Complete Blood Count (CBC)
Investigation Result Reference Value Unit
Primary Sample Type : Blood
HEMOGLOBIN
Hemoglobin (Hb) 12.5 Low 13.0 - 17.0 g/dL
RBC COUNT
Total RBC count 5.2 4.5 - 5.5 mill/cumm
BLOOD INDICES
Packed Cell Volume (PCV) 57.5 High 40 - 50 %
Mean Corpuscular Volume (MCV) 87.75 83 - 101 fL
Calculated
MCH 27.2 27 - 32 pg
Calculated
MCHC 32.8 32.5 - 34.5 g/dL
Calculated
RDW 13.6 11.6 - 14.0 %
Smart Pathology Laboratory
WBC COUNT
Total WBC count 9000 4000-11000 cumm
DIFFERENTIAL WBC COUNT
Drlogy.com
Neutrophils 60 50 - 62 %
Lymphocytes 31 20 - 40 %
Eosinophils 1 00 - 06 %
Monocytes 7 00 - 10 %
Basophils 1 00 - 02 %
PLATELET COUNT
Platelet Count 150000 Borderline 150000 - 410000 cumm
Instruments: Fully automated cell counter - Mindray 300
Interpretation: Further confirm for Anemia
Thanks for Reference ****End of Report****
Medical Lab Technician Dr. Payal Shah Dr. Vimal Shah
(DMLT, BMLT) (MD, Pathologist) (MD, Pathologist)
Generated on : 02 Dec, 202X 05:00 PM Page 1 of 1
Sample Collection 0123456789

In [7]:
import pdfplumber

pdf_path = "complete blood count report.pdf"

cbc_text = ""

with pdfplumber.open(pdf_path) as pdf:
    for page in pdf.pages:
        txt = page.extract_text()
        if txt:
            cbc_text += txt + "\n"

print("✔ CBC Report Extracted Successfully!\n")
print(cbc_text)

✔ CBC Report Extracted Successfully!

THE COMPLETE BLOOD COUNT SAMPLE REPORT 1. Name and address of the lab where the test was performed.
Tests may be run in a physician office lab, a lab located in a
Different laboratories gener T at h e e r e C p o o m rts p t le ha te t c B a l n o v o a d ry C g o re u a n t t ly S in a m ap p p l e e a R ra e n p c o e r a t n d in the order and kind of clinic or hospital, and/or samples may be sent to a reference
information included. This is one example of what a lab report for a Complete Blood Count may look like. laboratory for analysis.
NDaifmfeeres natn lda bpolraacteosr ieusse gde nhearvaet eb ereepno mrtsa dthea ut pca fno rv aillruys gtrraetaivtley ipnu arppopeseasr aonncley. aTnhde inn uthmeb oerrdeedr kaenyd tkoin tdh eo fr ight 2. Date this copy of the report was printed. This date may be
einxpfolraminast iao nfe iwnc olufd tehde. rTehpios rits eolneem eexnatsm. ple of what a lab report for a Complete Blood Count may look like. different than the date the results were generated, especially
Names and places used have been made up for illustrative purposes only. Point your cursor at a number on cumulative reports (those that include results of several
to learn about the different report elements. different tests run on different days).
3. Patient name or identifier. Links results to the correct person.
University Medical Center, Dept. of Pathology Report Date/Time:
1
123 University Way, City, ST 12345 02/10/2014 16:40 2 4. Patient identifier and identification number. Links results to
the correct person.
3 Name: Doe, John Q. Age/Sex: 73/M DOB: 01/01/1941 5. Name of doctor. The lab will send the results to the doctor(s)
4 Patient ID: 987654321 Status: 6 Routine or other healthcare practitioners listed.
5 Ordering Dr: Smith, Peter MD Physician Copy for: Smith, Jane MD
6. Status of the test request, such as Routine or STAT (perform
Y 10 test as rapidly as possible).
7 SPEC #: 223456 Collection Date/Time: 02/10/14 14:30
L 7. Unique identification number(s). Number(s) assigned to the
Received Date/Time: 02/10/14 15:00
11
sample(s) when it arrives at the laboratory.
SPECIMEN: Whole blood N
8
ORDERED: Complete Blood Count and White Blood Cell Differential 8. Test requested is a CBC and WBC differential.
9
QUERIES: [Comments and testing instructions]
O 9. Information about the person and blood sample. Any
pertinent information regarding the patient’s test preparation
15 16 17 or the condition of specimen may be noted here.
13 14
12 Test Normal A E bnormal Flag Units Reference Range 10. The date and time of sample collection
COMPLETE BLOOD COUNT L 11. The date and time that the laboratory received the sample.
White Blood Cell (WBC) 6.P9 K/mcL 4.8-10.8 12. A listing of the individual items that are being evaluated.
Red Blood Cell (RBC) 1.8 L M/mcL 4.7-6.1 Test names may be abbreviated on lab reports. You can look
Hemoglobin (HB/Hgb)) M 6.5 L** g/dL 14.0-18.0 for these test names or abbreviations in the pull-down menu
Hematocrit (HCT) 19.5 L** % 42-52 on the home page of this site or type the name into the
Mean Cell Volume (MCV) 109.6 H fL 80-100 search box to find information on specific tests.
Mean Cell HemogloAbin (MCH) 36.5 H pg 27.0-32.0
13. A listing of the CBC and differential results that are normal.
Mean Cell Hb Conc (MCHC) 33.3 g/dL 32.0-36.0
Red Cell DXist Width (RDW) 16.0 H % 11.5-14.5 14. A listing of the CBC and differential results that are abnormal.
Platelet count 180 K/mcL 150-450
15. An ‘H’ in this column may mean that the result is higher than
MEean Platelet Volume 7.9 fL 7.5-11.0
the reference range. ‘L’ may mean ‘low.’ Either represents a
result outside the reference range/value.
WBC Differential
Neutrophil (Neut) 50 % 33-73
16. Units of measurement (for quantitative results). The units of
Lymphocyte (Lymph) 36 % 13-52
measurement that labs use to report your results can vary
Monocyte (Mono) 8 % 0-10
from lab to lab. Regardless of the units that the lab uses, your
Eosinophil (Eos) 5 % 0-5
results will be interpreted in relation to the reference ranges
Basophil (Baso) 1 % 0-2
supplied by the laboratory.
Neutrophil, Absolute 3.5 K/mcL 1.8-7.8 17. Reference intervals (or reference ranges). These are the
Lymphocyte, Absolute 2.5 K/mcL 1.0-4.8 ranges in which “normal” values are expected to fall. The
Monocyte, Absolute 0.6 K/mcL 0-0.8 ranges that appear on your report are validated and supplied
Eosinophil, Absolute 0.4 K/mcL 0-0.45 by the laboratory that performed your test.
Basophil, Absolute 0.1 K/mcL 0-0.2
18. Critical results are dangerously abnormal results that must be
reported immediately to the responsible person, such as the
Flag Key: L= Abnormal Low, H= Abnormal High, **= critical value
ordering physician. The laboratory will often draw attention
Comment: **Hgb of 6.5 and Hct of 19.5 reported to Dr. J Smith at 15:20 on 2/10/14 by M. Peters 18 to such results with an asterisk (*) or something similar
and will usually note on the report the date and time the
** END OF REPORT **
responsible person was notified.

In [8]:
import pdfplumber

pdf_path = "Full body Report.pdf"

full_text = ""

with pdfplumber.open(pdf_path) as pdf:
    for i, page in enumerate(pdf.pages):
        txt = page.extract_text()
        if txt:
            full_text += txt + "\n"
            print(f"\n----- PAGE {i+1} -----\n")
            print(txt)

----- PAGE 1 -----

Laboratory Investigation Report
Patient Name : Mrs. Meena Sharma Centre : 2277 - Home Collection Dncr
Age/Gender : 53 Y 0 M 0 D /F OP/IP No/UHID : //
MaxID/Lab ID : ML04584243/2032042400426 Collection Date/Time: 04/Apr/2024 08:10AM
Ref Doctor : SELF Reporting Date/Time : 04/Apr/2024 03:25PM
Hematology
SIN No:B2B5138603
Wellwise Platinum Profile
Complete Haemogram, Peripheral Smear and ESR,EDTA
Date 04/Apr/2024 Unit Bio Ref Interval
08:10AM
Haemoglobin 8.3 g/dl 12.0 - 15.0
Modified cyanmethemoglobin
Packed Cell, Volume 28.5 % 40-50
Calculated
Total Leucocyte Count (TLC) 10.0 10~9/L 4.0-10.0
Electrical Impedance
RBC Count 4.75 10~12/L 3.8-4.8
Electrical Impedance
MCV 60.0 fL 83-101
Electrical Impedance
MCH 17.4 pg 27-32
Calculated
MCHC 29.0 g/dl 31.5-34.5
Calculated
Platelet Count 160 10~9/L 150-410
Electrical Impedance
MPV 10.7 fl 7.8-11.2
Calculated
RDW 20.8 % 11.5-14.5
Calculated
Differential Cell Count
VCS / Light Microscopy
Neutrophils 68 % 40-80
Lymphocytes 20 % 20-40
Monocytes 06 % 2-10
Eosinophils 06 % 1-6
Absolute Leukocyte Count
Calculated from TLC & DLC
Absolute Neutrophil Count 6.8 10~9/L 2.0-7.0
Absolute Lymphocyte Count 2.0 10~9/L 1.0-3.0
Absolute Monocyte Count 0.6 10~9/L 0.2-1.0
Absolute Eosinophil Count 0.6 10~9/L 0.02-0.5
ESR (Modified 12 mm/hr <=19
Westergren)
Peripheral Smear
Examination
RBC- Anisocytosis (++) Microcytes (+++) Hypochromia (+++)
WBC- Counts within normal limit
Page 1 of 21
(cid:55)(cid:72)(cid:86)(cid:87)(cid:3)(cid:51)(cid:72)(cid:85)(cid:73)(cid:82)(cid:85)(cid:80)(cid:72)(cid:71)(cid:3)(cid:68)(cid:87)(cid:3)(cid:29)(cid:20)(cid:19)(cid:25)(cid:19)(cid:3)(cid:16)(cid:3)(cid:48)(cid:68)(cid:91)(cid:3)(cid:43)(cid:82)(cid:86)(cid:83)(cid:76)(cid:87)(cid:68)(cid:79)(cid:3)(cid:54)(cid:75)(cid:68)(cid:79)(cid:76)(cid:80)(cid:68)(cid:85)(cid:3)(cid:37)(cid:68)(cid:74)(cid:75)(cid:15)(cid:3)(cid:48)(cid:68)(cid:91)(cid:3)(cid:47)(cid:68)(cid:69)
(cid:37)(cid:82)(cid:82)(cid:78)(cid:76)(cid:81)(cid:74)(cid:3)(cid:38)(cid:72)(cid:81)(cid:87)(cid:85)(cid:72)(cid:3)(cid:29)(cid:21)(cid:21)(cid:26)(cid:26)(cid:3)(cid:16)(cid:3)(cid:43)(cid:82)(cid:80)(cid:72)(cid:3)(cid:38)(cid:82)(cid:79)(cid:79)(cid:72)(cid:70)(cid:87)(cid:76)(cid:82)(cid:81)(cid:3)(cid:39)(cid:49)(cid:38)(cid:53)(cid:15)(cid:3)(cid:49)(cid:16)(cid:20)(cid:20)(cid:19)(cid:15)(cid:3)(cid:51)(cid:68)(cid:81)(cid:70)(cid:75)(cid:86)(cid:75)(cid:72)(cid:72)(cid:79)(cid:3)(cid:51)(cid:68)(cid:85)(cid:78)(cid:15)(cid:3)(cid:26)(cid:28)(cid:27)(cid:21)(cid:20)(cid:19)(cid:19)(cid:21)(cid:19)(cid:19)
(cid:55)(cid:75)(cid:72)(cid:3)(cid:68)(cid:88)(cid:87)(cid:75)(cid:72)(cid:81)(cid:87)(cid:76)(cid:70)(cid:76)(cid:87)(cid:92)(cid:3)(cid:82)(cid:73)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:85)(cid:72)(cid:83)(cid:82)(cid:85)(cid:87)(cid:3)(cid:70)(cid:68)(cid:81)(cid:3)(cid:69)(cid:72)(cid:3)(cid:89)(cid:72)(cid:85)(cid:76)(cid:73)(cid:76)(cid:72)(cid:71)(cid:3)(cid:69)(cid:92)(cid:3)(cid:86)(cid:70)(cid:68)(cid:81)(cid:81)(cid:76)(cid:81)(cid:74)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:52)(cid:3)(cid:53)(cid:3)(cid:38)(cid:82)(cid:71)(cid:72)(cid:3)(cid:82)(cid:81)(cid:3)(cid:87)(cid:82)(cid:83)(cid:3)(cid:82)(cid:73)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:83)(cid:68)(cid:74)(cid:72)

----- PAGE 2 -----

Laboratory Investigation Report
Patient Name : Mrs. Meena Sharma Centre : 2277 - Home Collection Dncr
Age/Gender : 53 Y 0 M 0 D /F OP/IP No/UHID : //
MaxID/Lab ID : ML04584243/2032042400426 Collection Date/Time: 04/Apr/2024 08:10AM
Ref Doctor : SELF Reporting Date/Time : 04/Apr/2024 03:25PM
Hematology
SIN No:B2B5138603
Wellwise Platinum Profile
Platelet- Adequate
Impression- Microcytic hypochromic anaemia
Advise- Serum Iron, Serum Ferritin and TIBC
Kindly correlate with clinical findings
*** End Of Report ***
Page 2 of 21
(cid:55)(cid:72)(cid:86)(cid:87)(cid:3)(cid:51)(cid:72)(cid:85)(cid:73)(cid:82)(cid:85)(cid:80)(cid:72)(cid:71)(cid:3)(cid:68)(cid:87)(cid:3)(cid:29)(cid:20)(cid:19)(cid:25)(cid:19)(cid:3)(cid:16)(cid:3)(cid:48)(cid:68)(cid:91)(cid:3)(cid:43)(cid:82)(cid:86)(cid:83)(cid:76)(cid:87)(cid:68)(cid:79)(cid:3)(cid:54)(cid:75)(cid:68)(cid:79)(cid:76)(cid:80)(cid:68)(cid:85)(cid:3)(cid:37)(cid:68)(cid:74)(cid:75)(cid:15)(cid:3)(cid:48)(cid:68)(cid:91)(cid:3)(cid:47)(cid:68)(cid:69)
(cid:37)(cid:82)(cid:82)(cid:78)(cid:76)(cid:81)(cid:74)(cid:3)(cid:38)(cid:72)(cid:81)(cid:87)(cid:85)(cid:72)(cid:3)(cid:29)(cid:21)(cid:21)(cid:26)(cid:26)(cid:3)(cid:16)(cid:3)(cid:43)(cid:82)(cid:80)(cid:72)(cid:3)(cid:38)(cid:82)(cid:79)(cid:79)(cid:72)(cid:70)(cid:87)(cid:76)(cid:82)(cid:81)(cid:3)(cid:39)(cid:49)(cid:38)(cid:53)(cid:15)(cid:3)(cid:49)(cid:16)(cid:20)(cid:20)(cid:19)(cid:15)(cid:3)(cid:51)(cid:68)(cid:81)(cid:70)(cid:75)(cid:86)(cid:75)(cid:72)(cid:72)(cid:79)(cid:3)(cid:51)(cid:68)(cid:85)(cid:78)(cid:15)(cid:3)(cid:26)(cid:28)(cid:27)(cid:21)(cid:20)(cid:19)(cid:19)(cid:21)(cid:19)(cid:19)
(cid:55)(cid:75)(cid:72)(cid:3)(cid:68)(cid:88)(cid:87)(cid:75)(cid:72)(cid:81)(cid:87)(cid:76)(cid:70)(cid:76)(cid:87)(cid:92)(cid:3)(cid:82)(cid:73)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:85)(cid:72)(cid:83)(cid:82)(cid:85)(cid:87)(cid:3)(cid:70)(cid:68)(cid:81)(cid:3)(cid:69)(cid:72)(cid:3)(cid:89)(cid:72)(cid:85)(cid:76)(cid:73)(cid:76)(cid:72)(cid:71)(cid:3)(cid:69)(cid:92)(cid:3)(cid:86)(cid:70)(cid:68)(cid:81)(cid:81)(cid:76)(cid:81)(cid:74)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:52)(cid:3)(cid:53)(cid:3)(cid:38)(cid:82)(cid:71)(cid:72)(cid:3)(cid:82)(cid:81)(cid:3)(cid:87)(cid:82)(cid:83)(cid:3)(cid:82)(cid:73)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:83)(cid:68)(cid:74)(cid:72)

----- PAGE 3 -----

Laboratory Investigation Report
Patient Name : Mrs. Meena Sharma Centre : 2277 - Home Collection Dncr
Age/Gender : 53 Y 0 M 0 D /F OP/IP No/UHID : //
MaxID/Lab ID : ML04584243/2032042400426 Collection Date/Time: 04/Apr/2024 08:10AM
Ref Doctor : SELF Reporting Date/Time : 04/Apr/2024 02:15PM
Clinical Biochemistry
SIN No:B2B5138603
Wellwise Platinum Profile
Fasting Blood Sugar (Glucose) , (FBS), Fluoride Plasma
Date 04/Apr/2024 Unit Bio Ref Interval
08:10AM
Glucose (Fasting) 102 mg/dL 74 - 99
HbA1c (Glycated/ Glycosylated Hemoglobin) Test
HPLC
Date 04/Apr/2024 Unit Bio Ref
08:10AM Interval
Glycosylated 5.0 % < 5.7
Haemoglobin(Hb A1c)
Glycosylated 31.13 mmol/mol < 39.0
Haemoglobin(Hb A1c) IFCC
Average Glucose Value For 96.8 mg/dL
the Last 3 Months
Average Glucose Value For 5.36 mmol/L
the Last 3 Months IFCC
Interpretation The following HbA1c ranges recommended by the American Diabetes Assocation(ADA) may be used as an aid in the diagnosis of diabetes
mellitus.
HbA1C(NGSP %) HbA1C(IFCC mmol/mol) Suggested Diagnosis
>6.5 >48 Diabetic
5.7 - 6.4 39 - 47 Pre- Diabetic
< 5.7 < 39 Non - Diabetic
HbA1C provides a useful index of average glycaemia over the preceding 6-8 weeks.
It is suggested that HbA1c is measured every 6 months in stable patients, every 3 months in patients with unstable metabolic control and every month in pregnancy.
Increased Glycated hemoglobin is a reflection of Hyperglycemia.
Kindly correlate with clinical findings
*** End Of Report ***
Page 3 of 21
(cid:55)(cid:72)(cid:86)(cid:87)(cid:3)(cid:51)(cid:72)(cid:85)(cid:73)(cid:82)(cid:85)(cid:80)(cid:72)(cid:71)(cid:3)(cid:68)(cid:87)(cid:3)(cid:29)(cid:20)(cid:19)(cid:25)(cid:19)(cid:3)(cid:16)(cid:3)(cid:48)(cid:68)(cid:91)(cid:3)(cid:43)(cid:82)(cid:86)(cid:83)(cid:76)(cid:87)(cid:68)(cid:79)(cid:3)(cid:54)(cid:75)(cid:68)(cid:79)(cid:76)(cid:80)(cid:68)(cid:85)(cid:3)(cid:37)(cid:68)(cid:74)(cid:75)(cid:15)(cid:3)(cid:48)(cid:68)(cid:91)(cid:3)(cid:47)(cid:68)(cid:69)
(cid:37)(cid:82)(cid:82)(cid:78)(cid:76)(cid:81)(cid:74)(cid:3)(cid:38)(cid:72)(cid:81)(cid:87)(cid:85)(cid:72)(cid:3)(cid:29)(cid:21)(cid:21)(cid:26)(cid:26)(cid:3)(cid:16)(cid:3)(cid:43)(cid:82)(cid:80)(cid:72)(cid:3)(cid:38)(cid:82)(cid:79)(cid:79)(cid:72)(cid:70)(cid:87)(cid:76)(cid:82)(cid:81)(cid:3)(cid:39)(cid:49)(cid:38)(cid:53)(cid:15)(cid:3)(cid:49)(cid:16)(cid:20)(cid:20)(cid:19)(cid:15)(cid:3)(cid:51)(cid:68)(cid:81)(cid:70)(cid:75)(cid:86)(cid:75)(cid:72)(cid:72)(cid:79)(cid:3)(cid:51)(cid:68)(cid:85)(cid:78)(cid:15)(cid:3)(cid:26)(cid:28)(cid:27)(cid:21)(cid:20)(cid:19)(cid:19)(cid:21)(cid:19)(cid:19)
(cid:55)(cid:75)(cid:72)(cid:3)(cid:68)(cid:88)(cid:87)(cid:75)(cid:72)(cid:81)(cid:87)(cid:76)(cid:70)(cid:76)(cid:87)(cid:92)(cid:3)(cid:82)(cid:73)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:85)(cid:72)(cid:83)(cid:82)(cid:85)(cid:87)(cid:3)(cid:70)(cid:68)(cid:81)(cid:3)(cid:69)(cid:72)(cid:3)(cid:89)(cid:72)(cid:85)(cid:76)(cid:73)(cid:76)(cid:72)(cid:71)(cid:3)(cid:69)(cid:92)(cid:3)(cid:86)(cid:70)(cid:68)(cid:81)(cid:81)(cid:76)(cid:81)(cid:74)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:52)(cid:3)(cid:53)(cid:3)(cid:38)(cid:82)(cid:71)(cid:72)(cid:3)(cid:82)(cid:81)(cid:3)(cid:87)(cid:82)(cid:83)(cid:3)(cid:82)(cid:73)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:83)(cid:68)(cid:74)(cid:72)

----- PAGE 4 -----

Laboratory Investigation Report
Patient Name : Mrs. Meena Sharma Centre : 2277 - Home Collection Dncr
Age/Gender : 53 Y 0 M 0 D /F OP/IP No/UHID : //
MaxID/Lab ID : ML04584243/2032042400426 Collection Date/Time: 04/Apr/2024 08:10AM
Ref Doctor : SELF Reporting Date/Time : 04/Apr/2024 02:54PM
Immunoassay
SIN No:B2B5138603
Wellwise Platinum Profile
Thyroid Profile*,Serum
Date 04/Apr/2024 Unit Bio Ref
08:10AM Interval
Free Triiodothyronine (FT3) 3.48 pg/mL 2.6 - 4.2
CLIA
Free Thyroxine (FT4) 0.81 ng/dL 0.58 - 1.64
CLIA
Thyroid Stimulating 7.281 (cid:151)(cid:44)(cid:56)(cid:18)(cid:80)(cid:47) 0.38 - 5.33
Hormone
CLIA
Comment
Premature Cord Blood
Upto 2 1st 2nd 3rd
Parameter Unit (28 - 36 (> 37
Month Trimester Trimester Trimester
weeks) weeks)
FT3 Pg/mL 0.15 - 3.91 2.4 - 5.6 2.11 - 3.83 1.96 - 3.38 1.96 - 3.38
FT4 ng/dl 1.7 - 4.0 0.7- 2.0 0.5 - 1.6 0.5 - 1.6
TSH uIU/ml 0.7 - 27.0 2.3 - 13.2 0.5 - 10 0.05 - 3.7 0.31 - 4.35 0.41 - 5.18
Note :(cid:3)(cid:55)(cid:54)(cid:43)(cid:3)(cid:79)(cid:72)(cid:89)(cid:72)(cid:79)(cid:86)(cid:3)(cid:68)(cid:85)(cid:72)(cid:3)(cid:86)(cid:88)(cid:69)(cid:77)(cid:72)(cid:70)(cid:87)(cid:3)(cid:87)(cid:82)(cid:3)(cid:70)(cid:76)(cid:85)(cid:70)(cid:68)(cid:71)(cid:76)(cid:68)(cid:81)(cid:3)(cid:3)(cid:89)(cid:68)(cid:85)(cid:76)(cid:68)(cid:87)(cid:76)(cid:82)(cid:81)(cid:15)(cid:3)(cid:85)(cid:72)(cid:68)(cid:70)(cid:75)(cid:76)(cid:81)(cid:74)(cid:3)(cid:83)(cid:72)(cid:68)(cid:78)(cid:3)(cid:79)(cid:72)(cid:89)(cid:72)(cid:79)(cid:86)(cid:3)(cid:69)(cid:72)(cid:87)(cid:90)(cid:72)(cid:72)(cid:81)(cid:3)(cid:21)(cid:3)(cid:177)(cid:3)(cid:23)(cid:3)(cid:68)(cid:80)(cid:3)
(cid:68)(cid:81)(cid:71)(cid:3)(cid:68)(cid:87)(cid:3)(cid:68)(cid:3)(cid:80)(cid:76)(cid:81)(cid:76)(cid:80)(cid:88)(cid:80)(cid:3)(cid:69)(cid:72)(cid:87)(cid:90)(cid:72)(cid:72)(cid:81)(cid:3)(cid:25)(cid:3)(cid:177)(cid:3)(cid:20)(cid:19)(cid:3)(cid:83)(cid:80)(cid:17)(cid:3)(cid:55)(cid:75)(cid:72)(cid:3)(cid:89)(cid:68)(cid:85)(cid:76)(cid:68)(cid:87)(cid:76)(cid:82)(cid:81)(cid:3)(cid:76)(cid:86)(cid:3)(cid:82)(cid:73)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:82)(cid:85)(cid:71)(cid:72)(cid:85)(cid:3)(cid:82)(cid:73)(cid:3)(cid:24)(cid:19)(cid:8)(cid:3)(cid:16)(cid:3)(cid:21)(cid:19)(cid:25)(cid:3)(cid:8)(cid:15)(cid:3)(cid:75)(cid:72)(cid:81)(cid:70)(cid:72)(cid:3)
time of the day has influence on the measured serum TSH concentrations.
Kindly correlate with clinical findings
*** End Of Report ***
Page 4 of 21
(cid:55)(cid:72)(cid:86)(cid:87)(cid:3)(cid:51)(cid:72)(cid:85)(cid:73)(cid:82)(cid:85)(cid:80)(cid:72)(cid:71)(cid:3)(cid:68)(cid:87)(cid:3)(cid:29)(cid:20)(cid:19)(cid:25)(cid:19)(cid:3)(cid:16)(cid:3)(cid:48)(cid:68)(cid:91)(cid:3)(cid:43)(cid:82)(cid:86)(cid:83)(cid:76)(cid:87)(cid:68)(cid:79)(cid:3)(cid:54)(cid:75)(cid:68)(cid:79)(cid:76)(cid:80)(cid:68)(cid:85)(cid:3)(cid:37)(cid:68)(cid:74)(cid:75)(cid:15)(cid:3)(cid:48)(cid:68)(cid:91)(cid:3)(cid:47)(cid:68)(cid:69)
(cid:37)(cid:82)(cid:82)(cid:78)(cid:76)(cid:81)(cid:74)(cid:3)(cid:38)(cid:72)(cid:81)(cid:87)(cid:85)(cid:72)(cid:3)(cid:29)(cid:21)(cid:21)(cid:26)(cid:26)(cid:3)(cid:16)(cid:3)(cid:43)(cid:82)(cid:80)(cid:72)(cid:3)(cid:38)(cid:82)(cid:79)(cid:79)(cid:72)(cid:70)(cid:87)(cid:76)(cid:82)(cid:81)(cid:3)(cid:39)(cid:49)(cid:38)(cid:53)(cid:15)(cid:3)(cid:49)(cid:16)(cid:20)(cid:20)(cid:19)(cid:15)(cid:3)(cid:51)(cid:68)(cid:81)(cid:70)(cid:75)(cid:86)(cid:75)(cid:72)(cid:72)(cid:79)(cid:3)(cid:51)(cid:68)(cid:85)(cid:78)(cid:15)(cid:3)(cid:26)(cid:28)(cid:27)(cid:21)(cid:20)(cid:19)(cid:19)(cid:21)(cid:19)(cid:19)
(cid:55)(cid:75)(cid:72)(cid:3)(cid:68)(cid:88)(cid:87)(cid:75)(cid:72)(cid:81)(cid:87)(cid:76)(cid:70)(cid:76)(cid:87)(cid:92)(cid:3)(cid:82)(cid:73)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:85)(cid:72)(cid:83)(cid:82)(cid:85)(cid:87)(cid:3)(cid:70)(cid:68)(cid:81)(cid:3)(cid:69)(cid:72)(cid:3)(cid:89)(cid:72)(cid:85)(cid:76)(cid:73)(cid:76)(cid:72)(cid:71)(cid:3)(cid:69)(cid:92)(cid:3)(cid:86)(cid:70)(cid:68)(cid:81)(cid:81)(cid:76)(cid:81)(cid:74)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:52)(cid:3)(cid:53)(cid:3)(cid:38)(cid:82)(cid:71)(cid:72)(cid:3)(cid:82)(cid:81)(cid:3)(cid:87)(cid:82)(cid:83)(cid:3)(cid:82)(cid:73)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:83)(cid:68)(cid:74)(cid:72)

----- PAGE 5 -----

Laboratory Investigation Report
Patient Name : Mrs. Meena Sharma Centre : 2277 - Home Collection Dncr
Age/Gender : 53 Y 0 M 0 D /F OP/IP No/UHID : //
MaxID/Lab ID : ML04584243/2032042400426 Collection Date/Time: 04/Apr/2024 08:10AM
Ref Doctor : SELF Reporting Date/Time : 04/Apr/2024 12:39PM
Clinical Biochemistry
SIN No:B2B5138603
Wellwise Platinum Profile
Kidney Function Test (KFT) Profile with Calcium, Uric Acid, Serum
Date 04/Apr/2024 Unit Bio Ref
08:10AM Interval
Urea 23.4 mg/dL 17.0 - 43.0
Urease, UV
Blood Urea Nitrogen 10.93 mg/dL 7.9 - 20.0
Urease, UV
Creatinine 0.56 mg/dL 0.6 - 1.1
Alkaline picrate kinetic
eGFR by MDRD 113.24 ml/min/1.73
MDRD (cid:80)(cid:240)
eGFR by CKD EPI 2021 109.06
Bun/CreatinineRatio 19.52 Ratio 12:1 - 20:1
Calculated
Uric Acid 4.5 mg/dL 2.6 - 6.0
Uricase, Colorimetric
Calcium (Total) 9.51 mg/dL 8.8 - 10.6
Arsenazo III
Sodium 139.9 mmol/L 136 - 146
ISE indirect
Potassium 4.58 mmol/L 3.5 - 5.1
ISE indirect
Chloride 105.7 mmol/L 101 - 109
ISE indirect
Bicarbonate 27.0 mmol/L 21 - 31
Enzymatic
Ref. Range (cid:72)(cid:42)(cid:41)(cid:53)(cid:3)(cid:16)(cid:3)(cid:40)(cid:86)(cid:87)(cid:76)(cid:80)(cid:68)(cid:87)(cid:72)(cid:71)(cid:3)(cid:42)(cid:79)(cid:82)(cid:80)(cid:72)(cid:85)(cid:88)(cid:79)(cid:68)(cid:85)(cid:3)(cid:41)(cid:76)(cid:79)(cid:87)(cid:72)(cid:85)(cid:68)(cid:87)(cid:76)(cid:82)(cid:81)(cid:3)(cid:53)(cid:68)(cid:87)(cid:72)(cid:3)(cid:76)(cid:86)(cid:3)(cid:70)(cid:68)(cid:79)(cid:70)(cid:88)(cid:79)(cid:68)(cid:87)(cid:72)(cid:71)(cid:3)(cid:69)(cid:92)(cid:3)(cid:48)(cid:39)(cid:53)(cid:39)(cid:3)(cid:72)(cid:84)(cid:88)(cid:68)(cid:87)(cid:76)(cid:82)(cid:81)(cid:3)(cid:90)(cid:75)(cid:76)(cid:70)(cid:75)(cid:3)(cid:76)(cid:86)(cid:3)(cid:80)(cid:82)(cid:86)(cid:87)(cid:3)(cid:68)(cid:70)(cid:70)(cid:88)(cid:85)(cid:68)(cid:87)(cid:72)(cid:3)(cid:73)(cid:82)(cid:85)(cid:3)(cid:42)(cid:41)(cid:53)(cid:86)(cid:3)(cid:148)(cid:3)(cid:3)(cid:25)(cid:19)(cid:80)(cid:79)(cid:3)(cid:18)(cid:3)(cid:80)(cid:76)(cid:81)(cid:3)(cid:18)(cid:20)(cid:17)(cid:26)(cid:22)(cid:3)(cid:80)(cid:240)(cid:17)(cid:48)(cid:39)(cid:53)(cid:39)
equation is used for adult population only.
(cid:31)(cid:25)(cid:19)(cid:80)(cid:79)(cid:3)(cid:18)(cid:3)(cid:80)(cid:76)(cid:81)(cid:3)(cid:18)(cid:3)(cid:20)(cid:17)(cid:26)(cid:22)(cid:3)(cid:80)(cid:240)(cid:3)(cid:16)(cid:3)(cid:38)(cid:75)(cid:85)(cid:82)(cid:81)(cid:76)(cid:70)(cid:3)(cid:46)(cid:76)(cid:71)(cid:81)(cid:72)(cid:92)(cid:3)(cid:39)(cid:76)(cid:86)(cid:72)(cid:68)(cid:86)(cid:72)
(cid:31)(cid:20)(cid:24)(cid:3)(cid:80)(cid:79)(cid:3)(cid:18)(cid:3)(cid:80)(cid:76)(cid:81)(cid:3)(cid:18)(cid:20)(cid:17)(cid:26)(cid:22)(cid:3)(cid:80)(cid:240)(cid:3)(cid:16)(cid:3)(cid:46)(cid:76)(cid:71)(cid:81)(cid:72)(cid:92)(cid:3)(cid:73)(cid:68)(cid:76)(cid:79)(cid:88)(cid:85)(cid:72)
BUN/Creatinine Ratio :-
Increased in reduced renal perfusion (e.g. dehydration, Hypovolemic shock, Congestive Heart Failure) or Obstructive
uropathy. Decreased in Acute Renal Tubular necrosis.
Page 5 of 21
(cid:55)(cid:72)(cid:86)(cid:87)(cid:3)(cid:51)(cid:72)(cid:85)(cid:73)(cid:82)(cid:85)(cid:80)(cid:72)(cid:71)(cid:3)(cid:68)(cid:87)(cid:3)(cid:29)(cid:20)(cid:19)(cid:25)(cid:19)(cid:3)(cid:16)(cid:3)(cid:48)(cid:68)(cid:91)(cid:3)(cid:43)(cid:82)(cid:86)(cid:83)(cid:76)(cid:87)(cid:68)(cid:79)(cid:3)(cid:54)(cid:75)(cid:68)(cid:79)(cid:76)(cid:80)(cid:68)(cid:85)(cid:3)(cid:37)(cid:68)(cid:74)(cid:75)(cid:15)(cid:3)(cid:48)(cid:68)(cid:91)(cid:3)(cid:47)(cid:68)(cid:69)
(cid:37)(cid:82)(cid:82)(cid:78)(cid:76)(cid:81)(cid:74)(cid:3)(cid:38)(cid:72)(cid:81)(cid:87)(cid:85)(cid:72)(cid:3)(cid:29)(cid:21)(cid:21)(cid:26)(cid:26)(cid:3)(cid:16)(cid:3)(cid:43)(cid:82)(cid:80)(cid:72)(cid:3)(cid:38)(cid:82)(cid:79)(cid:79)(cid:72)(cid:70)(cid:87)(cid:76)(cid:82)(cid:81)(cid:3)(cid:39)(cid:49)(cid:38)(cid:53)(cid:15)(cid:3)(cid:49)(cid:16)(cid:20)(cid:20)(cid:19)(cid:15)(cid:3)(cid:51)(cid:68)(cid:81)(cid:70)(cid:75)(cid:86)(cid:75)(cid:72)(cid:72)(cid:79)(cid:3)(cid:51)(cid:68)(cid:85)(cid:78)(cid:15)(cid:3)(cid:26)(cid:28)(cid:27)(cid:21)(cid:20)(cid:19)(cid:19)(cid:21)(cid:19)(cid:19)
(cid:55)(cid:75)(cid:72)(cid:3)(cid:68)(cid:88)(cid:87)(cid:75)(cid:72)(cid:81)(cid:87)(cid:76)(cid:70)(cid:76)(cid:87)(cid:92)(cid:3)(cid:82)(cid:73)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:85)(cid:72)(cid:83)(cid:82)(cid:85)(cid:87)(cid:3)(cid:70)(cid:68)(cid:81)(cid:3)(cid:69)(cid:72)(cid:3)(cid:89)(cid:72)(cid:85)(cid:76)(cid:73)(cid:76)(cid:72)(cid:71)(cid:3)(cid:69)(cid:92)(cid:3)(cid:86)(cid:70)(cid:68)(cid:81)(cid:81)(cid:76)(cid:81)(cid:74)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:52)(cid:3)(cid:53)(cid:3)(cid:38)(cid:82)(cid:71)(cid:72)(cid:3)(cid:82)(cid:81)(cid:3)(cid:87)(cid:82)(cid:83)(cid:3)(cid:82)(cid:73)(cid:3)(cid:87)(cid:75)(cid:72)(cid:3)(cid:83)(cid:68)(cid:74)(cid:72)

----- PAGE 6 -----

Laboratory Investigation Report
Patient Name : Mrs. Meena Sharma Centre : 2277 - Home Collection Dncr
Age/Gender : 53 Y 0 M 0 D /F OP/IP No/UHID : //
MaxID/Lab ID : ML04584243/2032042400426 Collection Date/Time: 04/Apr/2024 08:10AM
Ref Doctor : SELF Reporting Date/Time : 04/Apr/2024 12:38PM
Clinical Biochemistry
SIN No:B2B5138603
Wellwise Platinum Profile
Inorganic Phosphorus, Serum
Date 04/Apr/2024 Unit Bio Ref Interval
08:10AM
Phosphorus(inorg) 4.59 mg/dL 2.5 - 4.5
Phosphomolybdate-UV
Interpretation
Increased in Osteolytic metastatic bone tumors, myelogenous leukemia, sarcoidosis, milk-alkali syndrome, vitamin D intoxcation, healing fractures, renal failure,
hyperparathyroidism, PTH resistance (Pseudohypoparathyroidism) and diabetes mellitus with ketosis.
Decreased in Osteomalacia, steatorrhea, renal tubular acidosis, growth hormone deficiency, acute alcoholism, gram-negative bacterial septicemia, hypokalemia, familial
hypophosphatemic rickets, Vitamin D deficiency, severe malnutrition, malabsorption, secondary diarrhea, vomiting, nasogastric suction, primary hyperthyroidism
and PTH producing tumors.
Page 6 of 21
(cid:55)(cid:72)(cid:86)(cid:87)(cid:3)(cid:51)(cid:72)(cid:85)(cid:73)(cid:82)(cid:85)(cid:80)(cid:72)(cid:71)(cid:3)(cid:68)(cid:87)(cid:3)(cid:29)(cid:20)(cid:19)(cid:25)(cid:19)(cid:3)(cid:16)(cid:3)(cid:48)(cid:68)(cid:91)(cid:3)(cid:43)(cid:82)(cid:86)(cid:83)(cid:76)(cid:87)(cid:68)(cid:79)(cid:3)(cid:54)(cid:75)(cid:68)(cid:79)(cid:76)(cid:80)(cid:68)(cid:85)(cid:3)(cid:37)(cid:68)(cid:74)(cid:75)(cid:15)(cid:3)(cid:48)(cid:68)(cid:91)(cid:3)(cid:47)(cid:68)(cid:69)

In [9]:
!pip install nltk pandas regex

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (2025.11.3)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [10]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [11]:
!pip install pdfplumber pytesseract pdf2image
!apt-get update -qq
!apt-get install -y poppler-utils tesseract-ocr

Requirement already satisfied: pdfplumber in /usr/local/lib/python3.12/dist-packages (0.11.8)
Requirement already satisfied: pytesseract in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: pdf2image in /usr/local/lib/python3.12/dist-packages (1.17.0)
Requirement already satisfied: pdfminer.six==20251107 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (20251107)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Requirement already satisfied: pypdfium2>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (5.2.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251107->pdfplumber) (3.4.4)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251107->pdfplumber) (43.0.3)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from pytesseract) (25.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (2.23)
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
poppler-utils is already the newest version (22.02.0-2ubuntu0.12).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

In [12]:
from pdf2image import convert_from_path
import pytesseract

ocr_text = ""

pages = convert_from_path("CBC-lab-example report.pdf")

for i, page in enumerate(pages):
    print(f"--- OCR Page {i+1} ---")
    txt = pytesseract.image_to_string(page)
    ocr_text += txt + "\n"

print("✔ OCR extraction done!")

--- OCR Page 1 ---
✔ OCR extraction done!

In [13]:
import os

# If you already have variables cbc_text, full_text, drlogy_text from earlier cells, keep them.
# Otherwise this block will try to load corresponding .txt files saved earlier.
try:
    cbc_text
except NameError:
    if os.path.exists("complete blood count report.pdf.txt"):
        with open("complete blood count report.pdf.txt", "r", encoding="utf-8") as f:
            cbc_text = f.read()
    elif os.path.exists("complete blood count report.txt"):
        with open("complete blood count report.txt", "r", encoding="utf-8") as f:
            cbc_text = f.read()
    else:
        cbc_text = ""

try:
    full_text
except NameError:
    if os.path.exists("Full body Report.pdf.txt"):
        with open("Full body Report.pdf.txt", "r", encoding="utf-8") as f:
            full_text = f.read()
    elif os.path.exists("Full body Report.txt"):
        with open("Full body Report.txt", "r", encoding="utf-8") as f:
            full_text = f.read()
    else:
        full_text = ""

try:
    drlogy_text
except NameError:
    # OCR PDF might have saved as different name; try common filenames
    possible = ["CBC-lab-example report.pdf.txt",
                "CBC-lab-example report.txt",
                "CBC-lab-example report.txt",
                "CBC-lab-example report.txt"]
    drlogy_text = ""
    for p in possible:
        if os.path.exists(p):
            with open(p, "r", encoding="utf-8") as f:
                drlogy_text = f.read()
            break

# Pack into dict for easy loop
all_reports = {
    "CBC_Report": cbc_text,
    "Full_Body_Report": full_text,
    "OCR_CBC_Report": ocr_text
}

# Remove empty files (if OCR failed)
all_reports = {k: v for k, v in all_reports.items() if v and len(v.strip()) > 20}

print("Loaded reports:", list(all_reports.keys()))

Loaded reports: ['CBC_Report', 'Full_Body_Report', 'OCR_CBC_Report']

In [14]:
import re
from nltk.corpus import stopwords
from nltk import word_tokenize
from collections import Counter
from nltk.util import ngrams

STOP = set(stopwords.words('english'))

def clean_text_basic(text):
    # normalize whitespace, remove weird control chars
    text = text.replace('\r',' ').replace('\t',' ')
    text = re.sub(r'\s+', ' ', text)
    text = text.strip()
    return text

def tokenize_and_filter(text):
    text_l = text.lower()
    # remove punctuation except % and - and . inside numbers
    text_l = re.sub(r'[^a-z0-9%.\- ]+', ' ', text_l)
    tokens = word_tokenize(text_l)
    tokens = [t for t in tokens if t.isalnum() or (any(c.isdigit() for c in t) and '%' in t)==False]
    tokens = [t for t in tokens if t not in STOP and len(t)>1]
    return tokens

In [15]:
cbc_clean = clean_text_basic(cbc_text)
full_clean = clean_text_basic(full_text)
ocr_clean = clean_text_basic(ocr_text)   # 3rd PDF
print("Cleaning Done")

Cleaning Done

In [16]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [17]:
cbc_tokens = tokenize_and_filter(cbc_clean)
full_tokens = tokenize_and_filter(full_clean)
ocr_tokens = tokenize_and_filter(ocr_clean)   # 3rd PDF

In [18]:
print("CBC tokens:", cbc_tokens[:30])
print("Full Body Report tokens:", full_tokens[:30])
print("OCR CBC tokens:", ocr_tokens[:30])

CBC tokens: ['complete', 'blood', 'count', 'sample', 'report', '1.', 'name', 'address', 'lab', 'test', 'performed', 'tests', 'may', 'run', 'physician', 'office', 'lab', 'lab', 'located', 'different', 'laboratories', 'gener', 'rts', 'le', 'ha', 'te', 'ry', 'ly', 'ap', 'ra']
Full Body Report tokens: ['laboratory', 'investigation', 'report', 'patient', 'name', 'mrs.', 'meena', 'sharma', 'centre', '2277', 'home', 'collection', 'dncr', 'age', 'gender', '53', 'op', 'ip', 'uhid', 'maxid', 'lab', 'id', 'ml04584243', '2032042400426', 'collection', 'date', 'time', '04', 'apr', '2024']
OCR CBC tokens: ['drlogy', 'pathology', 'lab', '0123456789', '0912345678', 'accurate', 'caring', 'instant', 'drlogypathlab', 'drlogy.com', '105', '-108', 'smart', 'vision', 'complex', 'healthcare', 'road', 'opposite', 'healthcare', 'complex', 'mumbai', '689578', 'na', 'www.drlogy.com', 'yash', 'm.', 'patel', 'sample', 'collected', '125']

In [19]:
from collections import Counter

cbc_freq = Counter(cbc_tokens)
full_freq = Counter(full_tokens)
ocr_freq = Counter(ocr_tokens)

print("CBC Top Words:", cbc_freq.most_common(20))
print("\nFull Body Report Top Words:", full_freq.most_common(20))
print("\nOCR CBC Report Top Words:", ocr_freq.most_common(20))

CBC Top Words: [('results', 13), ('blood', 10), ('report', 10), ('lab', 10), ('test', 9), ('may', 9), ('date', 9), ('mcl', 8), ('reference', 7), ('cell', 7), ('count', 6), ('laboratory', 6), ('time', 6), ('complete', 5), ('sample', 5), ('name', 5), ('different', 5), ('person', 5), ('10', 5), ('14', 5)]

Full Body Report Top Words: [('cid', 5866), ('72', 499), ('68', 351), ('82', 313), ('87', 312), ('81', 257), ('76', 255), ('85', 215), ('75', 209), ('19', 163), ('79', 133), ('70', 133), ('86', 126), ('21', 112), ('15', 102), ('71', 101), ('74', 101), ('20', 100), ('80', 95), ('73', 93)]

OCR CBC Report Top Words: [('count', 8), ('02', 6), ('pm', 4), ('dec', 4), ('2x', 3), ('dr.', 3), ('shah', 3), ('blood', 3), ('cumm', 3), ('wbc', 3), ('00', 3), ('lab', 2), ('complex', 2), ('healthcare', 2), ('road', 2), ('sample', 2), ('collected', 2), ('31', 2), ('reference', 2), ('hemoglobin', 2)]

In [20]:
medical_parameters = [
    "hemoglobin","hb","wbc","rbc","platelet","mcv","mch","mchc",
    "rdw","neutrophils","lymphocytes","eosinophils","monocytes","basophils"
]

def find_params(tokens):
    return [t for t in tokens if t in medical_parameters]

print("CBC Parameters Found:", find_params(cbc_tokens))
print("Full Body Parameters Found:", find_params(full_tokens))
print("OCR CBC Parameters Found:", find_params(ocr_tokens))

CBC Parameters Found: ['wbc', 'wbc', 'rbc', 'hemoglobin', 'hb', 'mcv', 'mch', 'hb', 'mchc', 'rdw', 'platelet', 'platelet', 'wbc']
Full Body Parameters Found: ['rbc', 'mcv', 'mch', 'mchc', 'platelet', 'rdw', 'neutrophils', 'lymphocytes', 'monocytes', 'eosinophils', 'hemoglobin', 'hb', 'hb', 'hemoglobin', 'rbc']
OCR CBC Parameters Found: ['hemoglobin', 'hemoglobin', 'hb', 'rbc', 'rbc', 'mcv', 'mch', 'rdw', 'wbc', 'wbc', 'wbc', 'neutrophils', 'lymphocytes', 'eosinophils', 'monocytes', 'basophils', 'platelet', 'platelet']

In [21]:
def extract_numbers(tokens):
    return [t for t in tokens if any(c.isdigit() for c in t)]

print("CBC Numbers:", extract_numbers(cbc_tokens)[:20])
print("Full Body Numbers:", extract_numbers(full_tokens)[:20])
print("OCR Numbers:", extract_numbers(ocr_tokens)[:20])

CBC Numbers: ['1.', '2.', '3.', '123', '12345', '02', '10', '2014', '16', '40', '4.', '73', '01', '01', '1941', '5.', '987654321', '6.', '10', '223456']
Full Body Numbers: ['2277', '53', 'ml04584243', '2032042400426', '04', '2024', '08', '10am', '04', '2024', '03', '25pm', 'b2b5138603', '04', '2024', '08', '10am', '8.3', '12.0', '15.0']
OCR Numbers: ['0123456789', '0912345678', '105', '-108', '689578', '125', '039645', '62396', '784', '21', '02', '31', '02', '2x', '03', '11', '02', '2x', '555', '04']

In [22]:
from nltk.util import ngrams

def get_bigrams(tokens):
    bigs = list(ngrams(tokens, 2))
    return Counter(bigs).most_common(20)

print("CBC Bigrams:", get_bigrams(cbc_tokens))
print("\nFull Body Bigrams:", get_bigrams(full_tokens))
print("\nOCR CBC Bigrams:", get_bigrams(ocr_tokens))

CBC Bigrams: [(('date', 'time'), 6), (('complete', 'blood'), 5), (('blood', 'count'), 5), (('02', '10'), 3), (('10', '14'), 3), (('blood', 'cell'), 3), (('reference', 'range'), 3), (('mean', 'cell'), 3), (('lab', 'lab'), 2), (('lab', 'report'), 2), (('report', 'complete'), 2), (('count', 'may'), 2), (('may', 'look'), 2), (('look', 'like'), 2), (('links', 'results'), 2), (('results', 'correct'), 2), (('correct', 'person'), 2), (('report', 'date'), 2), (('identification', 'number'), 2), (('time', '02'), 2)]

Full Body Bigrams: [(('cid', 'cid'), 980), (('cid', '72'), 499), (('72', 'cid'), 476), (('cid', '68'), 350), (('68', 'cid'), 350), (('cid', '82'), 313), (('82', 'cid'), 313), (('cid', '87'), 312), (('87', 'cid'), 312), (('cid', '81'), 257), (('81', 'cid'), 257), (('cid', '76'), 255), (('76', 'cid'), 255), (('cid', '85'), 215), (('85', 'cid'), 215), (('cid', '75'), 208), (('75', 'cid'), 208), (('cid', '19'), 161), (('19', 'cid'), 161), (('cid', '79'), 133)]

OCR CBC Bigrams: [(('02', 'dec'), 4), (('pm', '02'), 3), (('dec', '2x'), 3), (('wbc', 'count'), 3), (('rbc', 'count'), 2), (('count', 'total'), 2), (('platelet', 'count'), 2), (('md', 'pathologist'), 2), (('drlogy', 'pathology'), 1), (('pathology', 'lab'), 1), (('lab', '0123456789'), 1), (('0123456789', '0912345678'), 1), (('0912345678', 'accurate'), 1), (('accurate', 'caring'), 1), (('caring', 'instant'), 1), (('instant', 'drlogypathlab'), 1), (('drlogypathlab', 'drlogy.com'), 1), (('drlogy.com', '105'), 1), (('105', '-108'), 1), (('-108', 'smart'), 1)]

In [23]:
def summary(tokens, title):
    print("\n📌 SUMMARY FOR:", title)
    print("Total Words:", len(tokens))
    print("Unique Words:", len(set(tokens)))
    print("Top 10 Words:", Counter(tokens).most_common(10))
    print("Total Numbers Found:", len(extract_numbers(tokens)))
    print("Total Medical Params Found:", len(find_params(tokens)))

summary(cbc_tokens, "CBC Report")
summary(full_tokens, "Full Body Report")
summary(ocr_tokens, "OCR CBC Report")

📌 SUMMARY FOR: CBC Report
Total Words: 573
Unique Words: 349
Top 10 Words: [('results', 13), ('blood', 10), ('report', 10), ('lab', 10), ('test', 9), ('may', 9), ('date', 9), ('mcl', 8), ('reference', 7), ('cell', 7)]
Total Numbers Found: 93
Total Medical Params Found: 13

📌 SUMMARY FOR: Full Body Report
Total Words: 13746
Unique Words: 992
Top 10 Words: [('cid', 5866), ('72', 499), ('68', 351), ('82', 313), ('87', 312), ('81', 257), ('76', 255), ('85', 215), ('75', 209), ('19', 163)]
Total Numbers Found: 5572
Total Medical Params Found: 15

📌 SUMMARY FOR: OCR CBC Report
Total Words: 210
Unique Words: 159
Top 10 Words: [('count', 8), ('02', 6), ('pm', 4), ('dec', 4), ('2x', 3), ('dr.', 3), ('shah', 3), ('blood', 3), ('cumm', 3), ('wbc', 3)]
Total Numbers Found: 60
Total Medical Params Found: 18

In [24]:
import re

parameter_pattern = re.compile(
    r"(?P<param>(?:[A-Za-z][A-Za-z \/\(\)\-]*))\s+"
    r"(?P<value>\d+\.?\d*)\s*"
    r"(?P<flag>Low|High|Borderline|L\\|H\\|L|H|Critical)?\s*"
    r"(?P<range>\d+\.?\d*\s*[-–]\s*\d+\.?\d*)?\s*"
    r"(?P<unit>[a-zA-Z/%µcuL]+)?",
    flags=re.IGNORECASE
)

In [25]:
def extract_parameters(text):
    results = []

    for m in parameter_pattern.finditer(text):
        param = m.group("param").strip()

        # Reject NON-medical lines
        if len(param.split()) > 4:
            continue
        if any(x in param.lower() for x in ["lab", "pathology", "medical", "address", "page", "report"]):
            continue

        results.append({
            "param": param,
            "value": m.group("value"),
            "flag": m.group("flag"),
            "range": m.group("range"),
            "unit": m.group("unit")
        })

    return results

In [26]:
cbc_params = extract_parameters(cbc_clean)
full_params = extract_parameters(full_clean)
ocr_params = extract_parameters(ocr_clean)

print("CBC Parameters Found:", len(cbc_params))
print("Full Body Report Parameters Found:", len(full_params))
print("OCR Report Parameters Found:", len(ocr_params))

CBC Parameters Found: 24
Full Body Report Parameters Found: 153
OCR Report Parameters Found: 17

In [27]:
import pandas as pd

def build_df(params, source):
    rows = []
    for p in params:
        rows.append({
            "Parameter": p["param"],
            "Value": p["value"],
            "Flag": p["flag"],
            "Reference Range": p["range"],
            "Unit": p["unit"],
            "Source": source
        })
    return rows

all_rows = []
all_rows += build_df(cbc_params, "CBC_Report")
all_rows += build_df(full_params, "Full_Body_Report")
all_rows += build_df(ocr_params, "OCR_CBC_Report")

df = pd.DataFrame(all_rows)
df

,Parameter,Value,Flag,Reference Range,Unit,Source
0,ST,12345,None,None,None,CBC_Report
1,Jane MD,6.,None,None,Status,CBC_Report
2,L,7.,None,None,Unique,CBC_Report
3,Whole blood N,8,None,None,ORDERED,CBC_Report
4,O,9.,None,None,Information,CBC_Report
...,...,...,...,...,...,...
189,Eosinophils,1,None,00 - 06,%,OCR_CBC_Report
190,Monocytes,7,None,00-10,%,OCR_CBC_Report
191,Basophils,1,None,00 - 02,%,OCR_CBC_Report
192,PLATELET COUNT Platelet Count,150000,Borderline,150000 - 410000,cumm,OCR_CBC_Report
193,X,05,None,None,None,OCR_CBC_Report

In [28]:
# List of real medical keywords
medical_keywords = [
    "hemoglobin", "hb", "rbc", "wbc", "platelet", "neutrophils",
    "lymphocytes", "monocytes", "basophils", "eosinophils",
    "mcv", "mch", "mchc", "rdw", "pcv", "hematocrit",
    "glucose", "cholesterol", "hdl", "ldl", "triglycerides"
]

# Function to check if row contains medical parameter
def is_medical(row):
    p = str(row["Parameter"]).lower()
    return any(key in p for key in medical_keywords)

# Apply filtering
clean_df = df[df.apply(is_medical, axis=1)]

# Remove empty values
clean_df = clean_df[clean_df["Value"].notnull()]

clean_df

,Parameter,Value,Flag,Reference Range,Unit,Source
6,White Blood Cell (WBC),6.,None,None,P,CBC_Report
8,Red Blood Cell (RBC),1.8,L,None,M/mcL,CBC_Report
10,Mean Cell HemogloAbin (MCH),36.5,H,None,pg,CBC_Report
11,Platelet count,180,None,None,K/mcL,CBC_Report
12,WBC Differential Neutrophil (Neut),50,None,None,%,CBC_Report
30,Electrical Impedance RBC Count,4.75,None,None,None,Full_Body_Report
32,Electrical Impedance MCV,60.0,None,None,fL,Full_Body_Report
33,Electrical Impedance MCH,17.4,None,None,pg,Full_Body_Report
34,Calculated MCHC,29.0,None,None,g/dl,Full_Body_Report
35,Calculated Platelet Count,160,None,None,None,Full_Body_Report
38,Calculated RDW,20.8,None,None,%,Full_Body_Report
39,Lymphocytes,20,None,None,%,Full_Body_Report
40,Monocytes,06,None,None,%,Full_Body_Report
41,Eosinophils,06,None,None,%,Full_Body_Report
55,AM Glucose (Fasting),102,None,None,mg/dL,Full_Body_Report
60,Average Glucose Value For,5.36,None,None,mmol/L,Full_Body_Report
111,AM Interval Cholesterol,154,None,None,mg/dL,Full_Body_Report
112,peroxidase HDL Cholesterol,47.9,None,None,mg/dL,Full_Body_Report
113,immunoinhibition LDL Cholesterol,97,None,None,mg/dL,Full_Body_Report
115,end point VLDL Cholesterol,22.8,None,None,mg/dL,Full_Body_Report
116,Calculated Total Cholesterol/HDL Ratio,3.2,None,None,None,Full_Body_Report
117,Calculated Non-HDL Cholesterol,106.10,None,None,mg/dL,Full_Body_Report
118,Calculated HDL/LDL,0.49,None,None,Ratio,Full_Body_Report
182,Blood HEMOGLOBIN Hemoglobin (Hb),12.5,Low,13.0-17.0,g/dL,OCR_CBC_Report
183,Mean Corpuscular Volume (MCV),87.75,None,83-101,fL,OCR_CBC_Report
184,Calculates MCH,27.2,None,27-32,pg,OCR_CBC_Report
186,Calculated RDW,13.6,None,11.6 - 14.0,%,OCR_CBC_Report
187,DIFFERENTIAL WBC COUNT Neutrophils,60,None,50 - 62,%,OCR_CBC_Report
188,Lymphocytes,31,None,20 - 40,%,OCR_CBC_Report
189,Eosinophils,1,None,00 - 06,%,OCR_CBC_Report
190,Monocytes,7,None,00-10,%,OCR_CBC_Report
191,Basophils,1,None,00 - 02,%,OCR_CBC_Report
192,PLATELET COUNT Platelet Count,150000,Borderline,150000 - 410000,cumm,OCR_CBC_Report

In [29]:
import re
import pandas as pd

cleaned_rows = []

def clean_unit(unit):
    if not unit: return None
    unit = unit.lower().strip()

    replacements = {
        "g/dl": "g/dL",
        "mg/dl": "mg/dL",
        "fl": "fL",
        "pg": "pg",
        "cumm": "cells/uL",
        "%": "%",
        "10^3/uL": "cells/uL"
    }

    for old, new in replacements.items():
        if old in unit:
            return new
    return unit


def clean_parameter_name(name):
    if not name: return None
    name = str(name)

    # Remove extra symbols
    name = re.sub(r"[^A-Za-z0-9 %/().-]", " ", name)

    # remove repeated words
    words = name.split()
    seen = set()
    filtered = []
    for w in words:
        if w.lower() not in seen:
            filtered.append(w)
            seen.add(w.lower())

    name = " ".join(filtered)

    # Map long names to standard short
    mapping = {
        "hemoglobin": "Hemoglobin",
        "blood hemoglobin": "Hemoglobin",
        "rbc count": "RBC Count",
        "wbc count": "WBC Count",
        "platelet count": "Platelet Count",
        "mean corpuscular volume": "MCV",
        "mean corpuscular hemoglobin": "MCH",
        "mean corpuscular hemoglobin concentration": "MCHC",
        "red cell distribution width": "RDW"
    }

    name_lower = name.lower()
    for key in mapping:
        if key in name_lower:
            return mapping[key]

    return name.strip()


def clean_value(value):
    if value is None: return None

    # Remove commas
    value = str(value).replace(",", "")

    # Extract number
    match = re.findall(r"\d+\.?\d*", value)
    if match:
        try:
            return float(match[0])
        except:
            return None
    return None


# ---- APPLY CLEANING ----
for _, row in clean_df.iterrows():
    cleaned_rows.append({
        "Parameter": clean_parameter_name(row["Parameter"]),
        "Value": clean_value(row["Value"]),
        "Flag": row["Flag"],
        "Reference Range": row["Reference Range"],
        "Unit": clean_unit(row["Unit"]),
        "Source": row["Source"]
    })

validated_df = pd.DataFrame(cleaned_rows)

validated_df

,Parameter,Value,Flag,Reference Range,Unit,Source
0,White Blood Cell (WBC),6.00,None,None,p,CBC_Report
1,Red Blood Cell (RBC),1.80,L,None,m/mcl,CBC_Report
2,Mean Cell HemogloAbin (MCH),36.50,H,None,pg,CBC_Report
3,Platelet Count,180.00,None,None,k/mcl,CBC_Report
4,WBC Differential Neutrophil (Neut),50.00,None,None,%,CBC_Report
5,RBC Count,4.75,None,None,None,Full_Body_Report
6,Electrical Impedance MCV,60.00,None,None,fL,Full_Body_Report
7,Electrical Impedance MCH,17.40,None,None,pg,Full_Body_Report
8,Calculated MCHC,29.00,None,None,g/dL,Full_Body_Report
9,Platelet Count,160.00,None,None,None,Full_Body_Report
10,Calculated RDW,20.80,None,None,%,Full_Body_Report
11,Lymphocytes,20.00,None,None,%,Full_Body_Report
12,Monocytes,6.00,None,None,%,Full_Body_Report
13,Eosinophils,6.00,None,None,%,Full_Body_Report
14,AM Glucose (Fasting),102.00,None,None,g/dL,Full_Body_Report
15,Average Glucose Value For,5.36,None,None,mmol/l,Full_Body_Report
16,AM Interval Cholesterol,154.00,None,None,g/dL,Full_Body_Report
17,peroxidase HDL Cholesterol,47.90,None,None,g/dL,Full_Body_Report
18,immunoinhibition LDL Cholesterol,97.00,None,None,g/dL,Full_Body_Report
19,end point VLDL Cholesterol,22.80,None,None,g/dL,Full_Body_Report
20,Calculated Total Cholesterol/HDL Ratio,3.20,None,None,None,Full_Body_Report
21,Calculated Non-HDL Cholesterol,106.10,None,None,g/dL,Full_Body_Report
22,Calculated HDL/LDL,0.49,None,None,ratio,Full_Body_Report
23,Hemoglobin,12.50,Low,13.0-17.0,g/dL,OCR_CBC_Report
24,MCV,87.75,None,83-101,fL,OCR_CBC_Report
25,Calculates MCH,27.20,None,27-32,pg,OCR_CBC_Report
26,Calculated RDW,13.60,None,11.6 - 14.0,%,OCR_CBC_Report
27,WBC Count,60.00,None,50 - 62,%,OCR_CBC_Report
28,Lymphocytes,31.00,None,20 - 40,%,OCR_CBC_Report
29,Eosinophils,1.00,None,00 - 06,%,OCR_CBC_Report
30,Monocytes,7.00,None,00-10,%,OCR_CBC_Report
31,Basophils,1.00,None,00 - 02,%,OCR_CBC_Report
32,Platelet Count,150000.00,Borderline,150000 - 410000,cells/uL,OCR_CBC_Report