In [1]:
import pandas as pd
df = pd.read_csv("contextual_analysis.csv")
df["Synthesized_Finding"] = (
    "Condition: " + df["Medical Condition"]
    + " | Pattern: " + df["Condition_Pattern"]
    + " | Risk: " + df["Contextual_Risk"]
)
df.to_csv("synthesis.csv", index=False)
print("Synthesis completed")
df.head()

Synthesis completed

,Name,Age,Gender,Blood Type,Medical Condition,Doctor,Hospital,Text_Length,Condition_Pattern,Risk_Level,Contextual_Risk,Synthesized_Finding
0,Bobby JacksOn,30,Male,B-,Cancer,Matthew Smith,Sons and Miller,6,Oncology Pattern,High Risk,High Risk (Gender Factor),Condition: Cancer | Pattern: Oncology Pattern ...
1,LesLie TErRy,62,Male,A+,Obesity,Samantha Davies,Kim Inc,7,Lifestyle Disorder Pattern,Low Risk,Low Risk,Condition: Obesity | Pattern: Lifestyle Disord...
2,DaNnY sMitH,76,Female,A-,Obesity,Tiffany Mitchell,Cook PLC,7,Lifestyle Disorder Pattern,Low Risk,Low Risk,Condition: Obesity | Pattern: Lifestyle Disord...
3,andrEw waTtS,28,Female,O+,Diabetes,Kevin Wells,"Hernandez Rogers and Vang,",8,General Health Pattern,Moderate Risk,Moderate Risk,Condition: Diabetes | Pattern: General Health ...
4,adrIENNE bEll,43,Female,AB+,Cancer,Kathleen Hanna,White-White,6,Oncology Pattern,High Risk,High Risk,Condition: Cancer | Pattern: Oncology Pattern ...

In [2]:
df = pd.read_csv("risk_assessment.csv")
def generate_recommendation(condition):
    if condition == "Diabetes":
        return "Monitor blood glucose, maintain balanced diet"
    elif condition == "Hypertension":
        return "Reduce salt intake, manage stress"
    elif condition == "Cancer":
        return "Follow oncologist guidance and treatment plan"
    elif condition == "Asthma":
        return "Avoid allergens, use inhaler as prescribed"
    else:
        return "Maintain healthy lifestyle"
df["Recommendation"] = df["Medical Condition"].apply(generate_recommendation)
df.to_csv("recommendation_generation.csv", index=False)
print("Recommendations generated")
df.head()

Recommendations generated

,Name,Age,Gender,Blood Type,Medical Condition,Doctor,Hospital,Text_Length,Condition_Pattern,Risk_Level,Recommendation
0,Bobby JacksOn,30,Male,B-,Cancer,Matthew Smith,Sons and Miller,6,Oncology Pattern,High Risk,Follow oncologist guidance and treatment plan
1,LesLie TErRy,62,Male,A+,Obesity,Samantha Davies,Kim Inc,7,Lifestyle Disorder Pattern,Low Risk,Maintain healthy lifestyle
2,DaNnY sMitH,76,Female,A-,Obesity,Tiffany Mitchell,Cook PLC,7,Lifestyle Disorder Pattern,Low Risk,Maintain healthy lifestyle
3,andrEw waTtS,28,Female,O+,Diabetes,Kevin Wells,"Hernandez Rogers and Vang,",8,General Health Pattern,Moderate Risk,"Monitor blood glucose, maintain balanced diet"
4,adrIENNE bEll,43,Female,AB+,Cancer,Kathleen Hanna,White-White,6,Oncology Pattern,High Risk,Follow oncologist guidance and treatment plan