Task 1

In [4]:
import pandas as pd
import json
import fitz
import os
def extract(file):
    ext = os.path.splitext(file)[1]
    if ext == ".csv":
        df = pd.read_csv(file)
        df.to_csv("output.csv", index=False)
        return df
    if ext == ".json":
        df = pd.read_json(file)
        df.to_csv("output.csv", index=False)
        return df
    if ext == ".pdf":
        text = ""
        for page in fitz.open(file):
            text += page.get_text()
        df = pd.DataFrame({"text": text.split("\n")})
        df.to_csv("output.csv", index=False)
        return df
data = extract("healthcare_dataset.csv")
data.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [5]:
import re
import pandas as pd
from collections import Counter
text = """
Healthcare data analysis is important.
Healthcare systems generate large amounts of data.
"""
text = text.lower()
text = re.sub(r'[^\w\s]', '', text)
words = text.split()
word_count = len(words)
unique_words = len(set(words))
common_words = Counter(words).most_common(5)
print("Total words:", word_count)
print("Unique words:", unique_words)
print("Most common words:", common_words)
df = pd.DataFrame(common_words, columns=["Word", "Frequency"])
df.to_csv("text_analysis_output.csv", index=False)
df.head()

Total words: 12
Unique words: 10
Most common words: [('healthcare', 2), ('data', 2), ('analysis', 1), ('is', 1), ('important', 1)]

         Word  Frequency
0  healthcare          2
1        data          2
2    analysis          1
3          is          1
4   important          1

In [6]:
import re
import pandas as pd
text = """
Healthcare data analysis is important.
Healthcare systems generate large amounts of data.
"""
text = text.lower()
text = re.sub(r'[^\w\s]', '', text)
tokens = text.split()
df = pd.DataFrame(tokens, columns=["tokens"])
df.to_csv("text_processing_output.csv", index=False)
df.head()

       tokens
0  healthcare
1        data
2    analysis
3          is
4   important

Task 2

In [10]:
import re
import pandas as pd
text = """
Patient Age: 45
Blood Pressure: 120/80
Heart Rate: 72
Cholesterol: 190
"""
pairs = re.findall(r'([\w\s]+):\s*([\w\/]+)', text)
df = pd.DataFrame(pairs, columns=["Parameter", "Value"])
df.to_csv("key_parameters_output.csv", index=False)
df

          Parameter   Value
0     \nPatient Age      45
1  \nBlood Pressure  120/80
2      \nHeart Rate      72
3     \nCholesterol     190

Task 3

In [11]:
import pandas as pd
data = {"Parameter":["Patient Age","Blood Pressure","Heart Rate","Cholesterol"],"Value":["45","120/80","72","190"]}
df = pd.DataFrame(data)
df["Value"] = df["Value"].astype(str)
df["Valid"] = df["Value"].apply(lambda x: x.strip() != "" and x.lower() != "nan")
df.to_csv("data_validation_output.csv", index=False)
df

        Parameter   Value  Valid
0     Patient Age      45   True
1  Blood Pressure  120/80   True
2      Heart Rate      72   True
3     Cholesterol     190   True

In [12]:
import pandas as pd
data = {"Parameter":["patient age","Blood pressure "," heart rate","Cholesterol level"],"Value":[" 45 ","120 / 80","72 bpm"," 190 mg/dl"]}
df = pd.DataFrame(data)
df["Parameter"] = df["Parameter"].str.lower().str.strip()
df["Value"] = df["Value"].str.lower().str.strip()
df["Value"] = df["Value"].str.replace("bpm","",regex=False)
df["Value"] = df["Value"].str.replace("mg/dl","",regex=False)
df["Value"] = df["Value"].str.replace(" ","",regex=False)
df.to_csv("standardized_data_output.csv", index=False)
df

           Parameter   Value
0        patient age      45
1     blood pressure  120/80
2         heart rate      72
3  cholesterol level     190