In [1]:
import pandas as pd
data = {"age":[45,60,35,55],"gender":["male","female","female","male"],"model1_flags":[1,2,0,2],"model2_score":[1,2,0,2],"model3_score":[1,1,0,1]}
df = pd.DataFrame(data)
df["overall_score"] = df["model1_flags"] + df["model2_score"] + df["model3_score"]
df["final_assessment"] = df["overall_score"].apply(lambda x: "Low Risk" if x <= 2 else "Moderate Risk" if x <= 4 else "High Risk")
df["summary"] = df.apply(lambda r: f"Age {r['age']}, {r['gender']} patient shows {r['final_assessment']} based on combined clinical parameters and contextual factors.", axis=1)
df.to_csv("findings_synthesis_output.csv", index=False)
df

,age,gender,model1_flags,model2_score,model3_score,overall_score,final_assessment,summary
0,45,male,1,1,1,3,Moderate Risk,"Age 45, male patient shows Moderate Risk based..."
1,60,female,2,2,1,5,High Risk,"Age 60, female patient shows High Risk based o..."
2,35,female,0,0,0,0,Low Risk,"Age 35, female patient shows Low Risk based on..."
3,55,male,2,2,1,5,High Risk,"Age 55, male patient shows High Risk based on ..."

In [2]:
import pandas as pd
data = {"age":[45,60,35,55],"gender":["male","female","female","male"],"final_assessment":["Low Risk","High Risk","Low Risk","Moderate Risk"]}
df = pd.DataFrame(data)
df["diet_recommendation"] = df["final_assessment"].apply(lambda x: "Maintain balanced diet" if x=="Low Risk" else "Low-fat, low-salt diet" if x=="Moderate Risk" else "Strict heart-healthy diet")
df["lifestyle_recommendation"] = df["final_assessment"].apply(lambda x: "Regular exercise" if x=="Low Risk" else "Increase physical activity and manage stress" if x=="Moderate Risk" else "Daily exercise, weight control, avoid smoking")
df["follow_up"] = df.apply(lambda r: "Annual check-up" if r["final_assessment"]=="Low Risk" else "Doctor review every 6 months" if r["final_assessment"]=="Moderate Risk" else "Immediate medical consultation and regular monitoring", axis=1)
df.to_csv("personalized_recommendations_output.csv", index=False)
df

,age,gender,final_assessment,diet_recommendation,lifestyle_recommendation,follow_up
0,45,male,Low Risk,Maintain balanced diet,Regular exercise,Annual check-up
1,60,female,High Risk,Strict heart-healthy diet,"Daily exercise, weight control, avoid smoking",Immediate medical consultation and regular mon...
2,35,female,Low Risk,Maintain balanced diet,Regular exercise,Annual check-up
3,55,male,Moderate Risk,"Low-fat, low-salt diet",Increase physical activity and manage stress,Doctor review every 6 months

In [3]:
import pandas as pd
data = {"finding":["Normal BP & Cholesterol","High BP","High Lipid Ratio","High BP & High Lipid Ratio"],"risk_level":["Low","Moderate","Moderate","High"]}
df = pd.DataFrame(data)
df["diet"] = df["finding"].apply(lambda x: "Balanced diet" if x=="Normal BP & Cholesterol" else "Low-salt diet" if x=="High BP" else "Low-fat diet" if x=="High Lipid Ratio" else "Strict heart-healthy diet")
df["lifestyle"] = df["finding"].apply(lambda x: "Maintain activity" if x=="Normal BP & Cholesterol" else "Increase physical activity" if x=="High BP" else "Exercise and weight control" if x=="High Lipid Ratio" else "Daily exercise, stress management")
df["follow_up"] = df["risk_level"].apply(lambda x: "Annual check-up" if x=="Low" else "Clinical review in 6 months" if x=="Moderate" else "Immediate medical consultation")
df["linked_summary"] = df.apply(lambda r: f"Finding: {r['finding']} → Diet: {r['diet']}, Lifestyle: {r['lifestyle']}, Follow-up: {r['follow_up']}", axis=1)
df.to_csv("recommendations_linked_to_findings.csv", index=False)
df

,finding,risk_level,diet,lifestyle,follow_up,linked_summary
0,Normal BP & Cholesterol,Low,Balanced diet,Maintain activity,Annual check-up,Finding: Normal BP & Cholesterol → Diet: Balan...
1,High BP,Moderate,Low-salt diet,Increase physical activity,Clinical review in 6 months,"Finding: High BP → Diet: Low-salt diet, Lifest..."
2,High Lipid Ratio,Moderate,Low-fat diet,Exercise and weight control,Clinical review in 6 months,Finding: High Lipid Ratio → Diet: Low-fat diet...
3,High BP & High Lipid Ratio,High,Strict heart-healthy diet,"Daily exercise, stress management",Immediate medical consultation,Finding: High BP & High Lipid Ratio → Diet: St...